defaults: ./dapo-gemma4-e2b-it-1n8g-fsdp2-automodel.yaml
policy:
  dtensor_cfg:
    context_parallel_size: 2
checkpointing:
  checkpoint_dir: results/dapo-gemma4-e2b-it-1n8g-fsdp2cp2-automodel
logger:
  log_dir: logs/dapo-gemma4-e2b-it-1n8g-fsdp2cp2-automodel
  wandb:
    name: dapo-gemma4-e2b-it-1n8g-fsdp2cp2-automodel
