defaults: ../../vlm_mpo.yaml
mpo:
  max_num_steps: 7000
  val_period: 100
  val_batches: 32
  val_global_batch_size: 32
  val_at_start: false
  val_at_end: true
  sft_average_log_probs: true
  preference_loss_weight: 0.8
  bco_loss_weight: 0.2
policy:
  train_global_batch_size: 256
  logprob_chunk_size: 128
  megatron_cfg:
    activation_checkpointing: true
    empty_unused_memory_level: 2
    bias_activation_fusion: false
    defer_fp32_logits: true
    optimizer:
      lr: 8.0e-07
      min_lr: 2.0e-09
    scheduler:
      lr_decay_style: cosine
      lr_warmup_iters: 50
      lr_warmup_init: 2.0e-09
    distributed_data_parallel_config:
      overlap_grad_reduce: false
      overlap_param_gather: false
checkpointing:
  checkpoint_dir: results/vlm_mpo_nemotron_omni_mmpr_megatron
  keep_top_k: 4
  save_period: 100
  checkpoint_must_save_by: 00:03:45:00
